### PR TITLE
refactor: convert \text{} to \textmath[]

### PR DESCRIPTION
**Pull request by OrangeX4**
Related to #46 and #128

### CODE REVIEW

**Comment by OrangeX4** [comment]
There is bugs in oi-wiki data, so i make it draft.

**Comment by Enter-tainer** [comment]
>  There is bug in test for oi-wiki, so i make it draft.

what's the bug?

**Comment by OrangeX4** [comment]
some escape bug, there are many escapes in text mode.

**Review by Enter-tainer — APPROVED** [review]
the test case looks good to me. Did you test oiwiki locally?

**Comment by Enter-tainer** [comment]
Will this fix #46 and #128 ?

**Comment by OrangeX4** [comment]
> the test case looks good to me. Did you test oiwiki locally?

Yes, there are no compilation errors.

**Comment by OrangeX4** [comment]
> Will this fix #46 and #128 ?

Fixed #128.

Fixed #46 partially, space at the end of `\text` is preserved.

But there is always one single space before `#textmath[]`, but i guess it should be another issue.

**Pull request merged**
